---
# tasks file for while_true_do.srv_podman

## Package Management
- name: Manage podman Packages
  package:
    name: "{{ wtd_srv_podman_package }}"
    state: "{{ wtd_srv_podman_package_state }}"
  become: true
  tags:
    - podman
    - package

- name: Include podman-docker Tasks
  include_tasks: podman-docker.yml
  when:
    - wtd_srv_podman_docker_package_state != "absent"
  tags:
    - podman
    - package
